baseURL = "https://latisaron.github.io/"
languageCode = "en-us"
title = "TURRIS"
theme = "PaperMod"

[params]
  defaultTheme = "auto"

  [params.homeInfoParams]
    Title = "TURRIS"
    Content = "Game development notes, reviews, and experiments."
